# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Testing Astronomy Questions over 3 AI Models"

prompts:
  - prompt1.yaml
  - prompt2.yaml
  - prompt3.yaml
  - prompt4.yaml
  - prompt5.yaml
  - prompt6.yaml
  - prompt7.yaml
  - prompt8.yaml
  - prompt9.yaml
  - prompt10.yaml
  - prompt11.yaml
  - prompt12.yaml
  # - "Answer the following question. This is very important to my career!: {{question}}"
  # - "You are an Astronomy expert. Answer the following question: {{question}}"
  # - "Answer the following question. Let's think step by step: {{question}}"

# setting this LLM as the judge
defaultTest:
  options:
    provider: openai:gpt-4o-mini

# testing over these 3 LLMs and using their respective variables for hyperparameters
providers:
  - id: "openai:gpt-4o-mini"
    config:
      temperature: 1.0
      max_tokens: 1000
      apiKeyEnvar: OPENAI_API_KEY
  - id: "anthropic:messages:claude-3-haiku-20240307"
    config:
      temperature: 1.0
      max_tokens: 1000
      apiKeyEnvar: ANTHROPIC_API_KEY
  # - id: "google:gemini-1.5-flash"
  #   config:
  #     temperature: 1.0
  #     maxOutputTokens: 1000
  #     apiKeyEnvar: GEMINI_API_KEY

tests: https://docs.google.com/spreadsheets/d/1sakFpeStGwuS0smwUGleA6gavlO1285kBPLmoiUq1aQ/edit?gid=0#gid=0

#storing the results
outputPath: results.csv
